version: 0.6.{build}

install:
    - cmd: cd Source
    - nuget restore

build:
  project: Source\MoreDotNet.sln
  verbosity: detailed

test_script: 
# generate report for XUnit testing framework:
    - cmd: packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"packages\xunit.runner.console.2.1.0\tools\xunit.console.exe" -targetargs:"MoreDotNet.Test\bin\debug\MoreDotNet.Tests.dll -parallel none -noshadow" -output:coverage.xml -searchdirs:".\Source\MoreDotNet.Test\bin\debug"; packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml

environment:
    repo_token:  
       secure: h0CL0d02rQ0lXPrpXJ4XeJfgpcvHAbjyry+FK1x+atkOeSjUOCUJVKwIUBjPSK6s