version: 0.6.{build}
skip_tags: true
configuration: Release
image: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - dotnet restore --packages \packages
build:
  project: .\MoreDotNet.sln
  verbosity: minimal
test_script:
  - dotnet test .\test\MoreDotNet.Test\MoreDotNet.Test.csproj
#    - .\packages\opencover\4.6.519\tools\OpenCover.Console.exe -register:user -target:".\packages\xunit.runner.console\2.2.0\tools\xunit.console.x86.exe" -targetargs:".\test\MoreDotNet.Test\bin\Release\netcoreapp1.1\MoreDotNet.Test.dll -noshadow -appveyor" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:.\MoreDotNet_coverage.xml
#    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
#    - pip install codecov
#    - codecov -f "MoreDotNet_coverage.xml"